import type { Metadata } from "next";
import { ArrowRight, ChevronRight } from "lucide-react";
import TrackedLink from "@/components/analytics/TrackedLink";
import { CORPORATE_GUIDE_BASE_PATH, CORPORATE_GUIDE_PUBLISHED_AT, CORPORATE_GUIDE_UPDATED_AT, corporateGuides } from "@/lib/corporate-guides";
import { SITE_NAME, SITE_URL } from "@/lib/site";

const title = "Özel Yazılım Karar Rehberleri";
const description = "Özel yazılım maliyetini, hazır ve özel yazılım seçimini, Excel ve manuel süreçlerden yazılıma geçişi tarafsız rehberlerle değerlendirin.";
export const metadata: Metadata = { title: { absolute: `${title} | ${SITE_NAME}` }, description, alternates: { canonical: `${SITE_URL}${CORPORATE_GUIDE_BASE_PATH}` }, robots: { index: true, follow: true }, openGraph: { title, description, url: `${SITE_URL}${CORPORATE_GUIDE_BASE_PATH}`, siteName: SITE_NAME, type: "article", locale: "tr_TR", images: [{ url: `${SITE_URL}/opengraph-image`, width: 1200, height: 630, alt: title }] }, twitter: { card: "summary_large_image", title, description, images: [`${SITE_URL}/opengraph-image`] } };
const schema = [{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Ana Sayfa", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Kurumsal", item: `${SITE_URL}/kurumsal` }, { "@type": "ListItem", position: 3, name: "Rehber", item: `${SITE_URL}${CORPORATE_GUIDE_BASE_PATH}` }] }, { "@context": "https://schema.org", "@type": "Article", headline: title, description, datePublished: CORPORATE_GUIDE_PUBLISHED_AT, dateModified: CORPORATE_GUIDE_UPDATED_AT, inLanguage: "tr-TR", mainEntityOfPage: `${SITE_URL}${CORPORATE_GUIDE_BASE_PATH}`, publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_URL } }];
export default function CorporateGuideHub() { return <main className="min-w-0 max-w-full overflow-x-clip bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><header className="border-b border-slate-200 bg-gradient-to-br from-white via-orange-50 to-orange-100 dark:border-slate-800 dark:from-slate-950 dark:via-slate-900 dark:to-orange-950/40"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><nav aria-label="Sayfa yolu" className="flex items-center gap-1 text-sm text-slate-600 dark:text-slate-300"><TrackedLink href="/">Ana Sayfa</TrackedLink><ChevronRight size={14} aria-hidden="true" /><TrackedLink href="/kurumsal">Kurumsal</TrackedLink><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">Rehber</span></nav><p className="mt-10 text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Araştırma ve karar merkezi</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight text-slate-950 dark:text-white sm:text-5xl">Özel Yazılım Karar Rehberleri</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-700 dark:text-slate-200">Satın alma kararı vermeden önce maliyet kapsamını, hazır ürün alternatifini ve operasyonel geçiş risklerini değerlendirin. Hizmet sayfalarından farklı olarak burada amaç satış değil, doğru kararı hazırlamaktır.</p><p className="mt-5 text-sm text-slate-500 dark:text-slate-400">Yayın ve güncelleme: 31 Ağustos 2026</p></div></header><section className="mx-auto max-w-6xl px-4 py-14 sm:px-6 lg:px-8"><h2 className="text-3xl font-black text-slate-950 dark:text-white">İhtiyacınıza uygun rehberi seçin</h2><div className="mt-8 grid min-w-0 gap-5 lg:grid-cols-3">{corporateGuides.map((guide) => <TrackedLink key={guide.slug} href={`${CORPORATE_GUIDE_BASE_PATH}/${guide.slug}`} className="group min-w-0 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-orange-300 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:border-slate-700 dark:bg-slate-900"><p className="text-xs font-bold uppercase tracking-wider text-[#B83A12] dark:text-orange-300">Karar rehberi</p><h2 className="mt-3 text-xl font-black text-slate-950 group-hover:text-[#B83A12] dark:text-white">{guide.shortTitle}</h2><p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{guide.description}</p><span className="mt-5 inline-flex items-center gap-1 font-bold text-[#B83A12] dark:text-orange-300">Rehberi okuyun <ArrowRight size={17} aria-hidden="true" /></span></TrackedLink>)}</div></section></main>; }
