import { ArrowRight, ChevronRight } from "lucide-react";
import TrackedLink from "@/components/analytics/TrackedLink";
import type { CorporateGuide } from "@/lib/corporate-guides";
import { CORPORATE_GUIDE_BASE_PATH, CORPORATE_GUIDE_PUBLISHED_AT, CORPORATE_GUIDE_UPDATED_AT } from "@/lib/corporate-guides";
import { SITE_NAME, SITE_URL } from "@/lib/site";

export function buildCorporateGuideSchema(guide: CorporateGuide) {
    const path = `${CORPORATE_GUIDE_BASE_PATH}/${guide.slug}`;
    return [
        { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Ana Sayfa", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "Kurumsal", item: `${SITE_URL}/kurumsal` }, { "@type": "ListItem", position: 3, name: "Rehber", item: `${SITE_URL}${CORPORATE_GUIDE_BASE_PATH}` }, { "@type": "ListItem", position: 4, name: guide.shortTitle, item: `${SITE_URL}${path}` }] },
        { "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.description, datePublished: CORPORATE_GUIDE_PUBLISHED_AT, dateModified: CORPORATE_GUIDE_UPDATED_AT, inLanguage: "tr-TR", mainEntityOfPage: `${SITE_URL}${path}`, publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_URL } },
        { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: guide.faq.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
    ];
}

export default function CorporateGuidePage({ guide }: { guide: CorporateGuide }) {
    const schema = buildCorporateGuideSchema(guide);
    return <main className="min-w-0 max-w-full overflow-x-clip bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
        <header className="border-b border-slate-200 bg-gradient-to-br from-white via-orange-50 to-orange-100 dark:border-slate-800 dark:from-slate-950 dark:via-slate-900 dark:to-orange-950/40"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><nav aria-label="Sayfa yolu" className="flex flex-wrap items-center gap-1 text-sm text-slate-600 dark:text-slate-300"><TrackedLink href="/">Ana Sayfa</TrackedLink><ChevronRight size={14} aria-hidden="true" /><TrackedLink href="/kurumsal">Kurumsal</TrackedLink><ChevronRight size={14} aria-hidden="true" /><TrackedLink href={CORPORATE_GUIDE_BASE_PATH}>Rehber</TrackedLink><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">{guide.shortTitle}</span></nav><p className="mt-10 text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Karar rehberi</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight text-slate-950 dark:text-white sm:text-5xl">{guide.title}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-700 dark:text-slate-200">{guide.intro}</p><p className="mt-5 text-sm text-slate-500 dark:text-slate-400"><time dateTime={CORPORATE_GUIDE_PUBLISHED_AT}>Yayın: 31 Ağustos 2026</time> · <time dateTime={CORPORATE_GUIDE_UPDATED_AT}>Güncelleme: 31 Ağustos 2026</time></p></div></header>
        <div className="mx-auto grid min-w-0 max-w-6xl gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[15rem_minmax(0,1fr)] lg:px-8">
            <aside className="min-w-0"><nav aria-label="İçindekiler" className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900 lg:sticky lg:top-24"><h2 className="font-black text-slate-950 dark:text-white">İçindekiler</h2><ol className="mt-4 space-y-2 text-sm">{guide.sections.map((section) => <li key={section.id}><a href={`#${section.id}`} className="block rounded px-1 py-1 text-slate-600 hover:text-[#B83A12] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300 dark:text-slate-300">{section.title}</a></li>)}</ol></nav></aside>
            <article className="min-w-0 max-w-3xl space-y-12">
                {guide.sections.map((section) => <section id={section.id} key={section.id} className="scroll-mt-24"><h2 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-4 leading-8 text-slate-700 dark:text-slate-300">{paragraph}</p>)}{section.bullets && <ul className="mt-5 list-disc space-y-2 pl-6 leading-7 text-slate-700 marker:text-[#B83A12] dark:text-slate-300">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}
                {guide.table && <section aria-labelledby="karar-tablosu"><h2 id="karar-tablosu" className="text-2xl font-black text-slate-950 dark:text-white sm:text-3xl">Karar tablosu</h2><div className="mt-5 max-w-full overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-700"><table className="w-full border-collapse text-left text-sm"><caption className="bg-orange-50 p-4 text-left font-bold text-slate-950 dark:bg-orange-950/30 dark:text-white">{guide.table.caption}</caption><thead className="bg-slate-100 dark:bg-slate-800"><tr>{guide.table.headers.map((header) => <th key={header} scope="col" className="whitespace-normal p-4 font-black">{header}</th>)}</tr></thead><tbody>{guide.table.rows.map((row) => <tr key={row[0]} className="border-t border-slate-200 dark:border-slate-700">{row.map((cell, index) => index === 0 ? <th key={cell} scope="row" className="p-4 font-bold">{cell}</th> : <td key={cell} className="p-4 text-slate-600 dark:text-slate-300">{cell}</td>)}</tr>)}</tbody></table></div></section>}
                <section className="rounded-3xl bg-[#7E2D13] p-6 text-white sm:p-8"><h2 className="text-2xl font-black">İhtiyacınızı somutlaştırın</h2><p className="mt-3 leading-relaxed text-orange-50">Seçeneklerinizi adım adım işaretleyerek kapsam seviyesini ve olası ilk fazı görün ya da mevcut sürecinizi doğrudan anlatın.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><TrackedLink href="/kurumsal/yazilim-projesi-kapsam-hesaplama" corporateAnalytics={{ form_type: "corporate", service: guide.slug, cta_location: "guide_estimator" }} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-[#7E2D13] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200">Proje kapsamınızı hesaplayın <ArrowRight size={18} aria-hidden="true" /></TrackedLink><TrackedLink href="/iletisim?konu=kurumsal-yazilim" corporateAnalytics={{ form_type: "corporate", service: guide.slug, cta_location: "guide_contact" }} className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/50 px-5 py-3 font-bold text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/60">Sürecinizi anlatın</TrackedLink></div></section>
                <section><h2 className="text-2xl font-black text-slate-950 dark:text-white sm:text-3xl">İlgili sayfalar</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{guide.relatedLinks.map((link) => <TrackedLink key={link.href} href={link.href} className="rounded-2xl border border-slate-200 bg-white p-5 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-black text-slate-950 dark:text-white">{link.label}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{link.description}</p></TrackedLink>)}</div></section>
                <section><h2 className="text-2xl font-black text-slate-950 dark:text-white sm:text-3xl">Sık sorulan sorular</h2><div className="mt-5 space-y-4">{guide.faq.map((item) => <article key={item.question} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-black text-slate-950 dark:text-white">{item.question}</h3><p className="mt-2 leading-relaxed text-slate-600 dark:text-slate-300">{item.answer}</p></article>)}</div></section>
            </article>
        </div>
    </main>;
}
