import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, ChevronRight } from "lucide-react";
import type { BusinessSolution } from "@/lib/business-solutions";
import { getSolutionContactPath } from "@/lib/business-solutions";
import { getCorporateService } from "@/lib/corporate-services";
import TrackedLink from "@/components/analytics/TrackedLink";
import SolutionSchema from "./SolutionSchema";

function CardList({ title, intro, items }: { title: string; intro?: string; items: string[] }) {
    return <section><h2 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">{title}</h2>{intro ? <p className="mt-3 max-w-3xl leading-relaxed text-slate-600 dark:text-slate-300">{intro}</p> : null}<div className="mt-6 grid min-w-0 gap-3 sm:grid-cols-2">{items.map(item => <div key={item} className="flex min-w-0 gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-900"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-orange-100 text-[#B83A12] dark:bg-orange-950 dark:text-orange-300"><Check size={15} aria-hidden="true" /></span><span className="min-w-0 break-words text-sm font-medium leading-relaxed text-slate-700 dark:text-slate-200">{item}</span></div>)}</div></section>;
}

export default function SolutionPage({ solution }: { solution: BusinessSolution }) {
    const related = solution.relatedServices.flatMap(slug => { const service = getCorporateService(slug); return service ? [service] : []; });
    const contactPath = getSolutionContactPath(solution);
    return <main className="min-w-0 max-w-full overflow-x-clip bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
        <SolutionSchema solution={solution} />
        <section className="border-b border-slate-200 bg-gradient-to-br from-white via-orange-50 to-orange-100 dark:border-slate-800 dark:from-slate-950 dark:via-slate-900 dark:to-orange-950/40"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><nav aria-label="Sayfa yolu" className="flex flex-wrap items-center gap-1 text-sm text-slate-600 dark:text-slate-300"><Link href="/" className="rounded-sm hover:text-[#B83A12] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#B83A12]">Ana Sayfa</Link><ChevronRight size={14} aria-hidden="true" /><Link href="/cozumler" className="rounded-sm hover:text-[#B83A12] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#B83A12]">Çözümler</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">{solution.shortTitle}</span></nav><div className="mt-10 grid min-w-0 items-center gap-10 lg:grid-cols-[minmax(0,1.2fr)_minmax(280px,.8fr)]"><div className="min-w-0"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">HesapMod İşletme Çözümleri</p><h1 className="mt-4 max-w-full break-words text-4xl font-black tracking-tight text-slate-950 dark:text-white sm:text-5xl lg:text-6xl">{solution.title}</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-700 dark:text-slate-200 sm:text-xl">{solution.shortDescription}</p><TrackedLink href={contactPath} eventName="solution_cta_click" analytics={{ solution: solution.slug }} className="mt-8 inline-flex min-h-12 max-w-full items-center justify-center gap-2 rounded-xl bg-[#B83A12] px-6 py-3 text-center font-bold text-white transition hover:bg-[#962F10] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-300">{solution.cta.label} <ArrowRight size={18} aria-hidden="true" /></TrackedLink></div><aside className="min-w-0 rounded-2xl border border-orange-200 bg-white/80 p-6 shadow-sm backdrop-blur dark:border-orange-900 dark:bg-slate-900/80" aria-labelledby="impact-title"><h2 id="impact-title" className="text-lg font-black text-slate-950 dark:text-white">İşletmeye etkisi</h2><ul className="mt-5 space-y-4">{solution.businessImpact.map(item => <li key={item} className="flex gap-3 text-sm font-medium leading-relaxed text-slate-700 dark:text-slate-200"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-[#B83A12] dark:text-orange-300" aria-hidden="true" /><span>{item}</span></li>)}</ul></aside></div></div></section>
        <div className="mx-auto grid min-w-0 max-w-7xl gap-14 px-4 py-14 sm:px-6 sm:py-20 lg:px-8">
            <CardList title="İşletme hangi sorunları yaşıyor?" intro="Sorunlar çoğu zaman tek bir araçtan değil, sürecin parçalı ve görünmez kalmasından kaynaklanır." items={solution.problems} />
            <section className="rounded-3xl bg-slate-950 p-6 text-white sm:p-10 dark:border dark:border-slate-800"><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-300">Çözüm yaklaşımı</p><h2 className="mt-3 text-2xl font-black tracking-tight sm:text-3xl">HesapMod nasıl bir sistem geliştirebilir?</h2><p className="mt-4 max-w-4xl leading-relaxed text-slate-200">{solution.approach}</p></section>
            <div className="grid min-w-0 gap-12 lg:grid-cols-2"><CardList title="Kullanılabilecek uygulama seçenekleri" items={solution.deliveryOptions} /><CardList title="Temel özellikler" items={solution.features} /></div>
            <section><h2 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">Proje nasıl ilerler?</h2><ol className="mt-6 grid min-w-0 gap-4 md:grid-cols-2">{solution.process.map((item,index) => <li key={item} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><span className="text-sm font-black text-[#B83A12] dark:text-orange-300">0{index+1}</span><p className="mt-2 leading-relaxed text-slate-700 dark:text-slate-200">{item}</p></li>)}</ol></section>
            <div className="grid min-w-0 gap-12 lg:grid-cols-2"><CardList title="Uygun sektör örnekleri" intro="Çözüm tek bir sektöre değil, benzer operasyon sorunlarına uyarlanır." items={solution.industries} /><CardList title="Teslim edilebilecek çıktılar" intro="Kesin kapsam ihtiyaç analizi sonrasında netleştirilir." items={solution.deliverables} /></div>
            <section><h2 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">Sık sorulan sorular</h2><div className="mt-6 space-y-3">{solution.faq.map(item => <details key={item.question} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><summary className="cursor-pointer list-none rounded-sm pr-8 font-bold text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#B83A12] dark:text-white">{item.question}</summary><p className="mt-3 leading-relaxed text-slate-600 dark:text-slate-300">{item.answer}</p></details>)}</div></section>
            <section><h2 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">İlgili kurumsal hizmetler</h2><div className="mt-6 grid min-w-0 gap-4 md:grid-cols-3">{related.map(service => <Link key={service.slug} href={`/kurumsal/${service.slug}`} className="group min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-orange-300 hover:shadow-md focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold text-slate-950 group-hover:text-[#B83A12] dark:text-white">{service.shortTitle}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{service.shortDescription}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#B83A12] dark:text-orange-300">Hizmeti incele <ArrowRight size={15} aria-hidden="true" /></span></Link>)}</div></section>
            <section className="min-w-0 rounded-3xl bg-gradient-to-br from-[#352018] via-[#743920] to-[#CC4A1A] px-6 py-10 text-white shadow-xl sm:px-10 lg:flex lg:items-center lg:justify-between lg:gap-10"><div className="min-w-0 max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-100">Proje talebi</p><h2 className="mt-3 text-2xl font-black tracking-tight sm:text-3xl">Sürecinizi birlikte netleştirelim</h2><p className="mt-3 leading-relaxed text-orange-50">Mevcut işleyişi, kullanıcıları ve öncelikleri paylaşın. Uygun teknik yaklaşımı birlikte değerlendirelim.</p></div><TrackedLink href={contactPath} eventName="solution_cta_click" analytics={{ solution: solution.slug, source: "bottom" }} className="mt-6 inline-flex min-h-12 max-w-full items-center justify-center gap-2 rounded-xl bg-white px-6 py-3 text-center font-bold text-[#9E3515] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/60 lg:mt-0">{solution.cta.label} <ArrowRight size={18} aria-hidden="true" /></TrackedLink></section>
        </div>
    </main>;
}
