import type { Metadata } from "next";
import Link from "@/components/analytics/TrackedLink";
import { ArrowRight, ChevronRight, Factory, ShoppingCart, Truck, Wrench } from "lucide-react";
import { businessSolutions } from "@/lib/business-solutions";
import { corporateServices, CORPORATE_CONTACT_PATH } from "@/lib/corporate-services";
import { SITE_NAME, SITE_URL } from "@/lib/site";

const title = "İşletmeler İçin Yazılım ve Otomasyon Çözümleri";
const description = "Excel, manuel operasyon, stok, sipariş, saha, teklif ve raporlama sorunları için işletmenize uygun yazılım ve otomasyon çözümleri.";

export const metadata: Metadata = {
    title: { absolute: `${title} | ${SITE_NAME}` }, description,
    alternates: { canonical: `${SITE_URL}/cozumler` },
    openGraph: { title, description, url: `${SITE_URL}/cozumler`, siteName: SITE_NAME, type: "website", locale: "tr_TR", images: [{ url: `${SITE_URL}/opengraph-image`, width: 1200, height: 630, alt: title }] },
    twitter: { card: "summary_large_image", title, description, images: [`${SITE_URL}/opengraph-image`] },
};

const sectors = [
    ["Üretim ve sanayi", "Üretim, stok ve kalite kayıtlarını ortak akışta izleme"], ["Tekstil", "Sipariş, numune, üretim ve sevkiyat durumlarını takip etme"], ["Lojistik ve taşımacılık", "Görev, araç, teslimat ve saha bildirimlerini yönetme"], ["İnşaat", "Şantiye, ekip, malzeme ve ilerleme kayıtlarını merkezileştirme"], ["Perakende ve e-ticaret", "Sipariş, stok ve kanal verilerini birleştirme"], ["Toptan satış", "Teklif, sipariş, depo ve müşteri süreçlerini izleme"], ["Teknik servis", "Servis kaydı, saha görevi ve parça kullanımını takip etme"], ["Eğitim", "Başvuru, planlama, öğrenci ve operasyon süreçlerini yönetme"], ["Sağlık", "Yetkili iş akışları, görevler ve operasyon kayıtlarını düzenleme"], ["Turizm", "Rezervasyon sonrası görev ve hizmet operasyonlarını koordine etme"], ["Profesyonel hizmetler", "Müşteri, teklif, proje ve iş yükünü takip etme"], ["Saha ekipleri bulunan işletmeler", "Mobil görev, form, fotoğraf ve durum verisini toplama"],
];

const schema = [
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Ana Sayfa", item: SITE_URL }, { "@type": "ListItem", position: 2, name: "İşletme Çözümleri", item: `${SITE_URL}/cozumler` }] },
    { "@context": "https://schema.org", "@type": "Service", name: title, description, url: `${SITE_URL}/cozumler`, inLanguage: "tr-TR", provider: { "@type": "Organization", name: SITE_NAME, url: SITE_URL }, areaServed: { "@type": "Country", name: "Türkiye" } },
];

export default function SolutionsPage() {
    return <main className="min-w-0 max-w-full overflow-x-clip bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
        <section className="relative overflow-hidden bg-gradient-to-br from-[#211712] via-[#68361F] to-[#B83A12] text-white"><div className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8"><nav aria-label="Sayfa yolu" className="flex items-center gap-1 text-sm text-orange-100"><Link href="/" className="rounded-sm hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Ana Sayfa</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">Çözümler</span></nav></div><div className="mx-auto max-w-7xl px-4 pb-16 pt-10 sm:px-6 sm:pb-24 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-orange-200">HesapMod İşletme Çözümleri</p><h1 className="mt-5 max-w-5xl text-4xl font-black leading-tight tracking-tight sm:text-5xl lg:text-6xl">İş sorunlarını ölçülebilir yazılım süreçlerine dönüştürün</h1><p className="mt-6 max-w-3xl text-xl leading-relaxed text-orange-50">Manuel iş yükünü, dağınık veriyi ve görünmeyen operasyonu işletmenizin gerçek akışına uygun web, mobil, masaüstü ve entegrasyon çözümleriyle ele alıyoruz.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="#cozumler" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-6 py-3 font-bold text-[#9E3515] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/60">Çözümleri İnceleyin <ArrowRight size={18} aria-hidden="true" /></Link><Link href={CORPORATE_CONTACT_PATH} className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/40 px-6 py-3 font-bold text-white hover:bg-white/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/50">Sürecinizi Anlatın</Link></div></div></section>
        <section id="cozumler" className="scroll-mt-24"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Yüksek etkili kullanım alanları</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">Sorundan başlayan çözüm başlıkları</h2><p className="mt-4 leading-relaxed text-slate-600 dark:text-slate-300">Önce yaşanan iş kaybını ve süreci anlarız; teknoloji seçimini bu ihtiyaca göre yaparız.</p></div><div className="mt-8 grid min-w-0 gap-4 md:grid-cols-2 xl:grid-cols-3">{businessSolutions.map(solution => <Link key={solution.slug} href={`/cozumler/${solution.slug}`} className="group min-w-0 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-orange-300 hover:shadow-lg focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:border-slate-700 dark:bg-slate-900"><h3 className="break-words text-lg font-black text-slate-950 group-hover:text-[#B83A12] dark:text-white">{solution.shortTitle}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{solution.shortDescription}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#B83A12] dark:text-orange-300">Çözümü incele <ArrowRight size={15} aria-hidden="true" /></span></Link>)}</div></div></section>
        <section className="border-y border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Sektör örnekleri</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">Farklı sektörlerde benzer operasyon sorunları</h2><p className="mt-4 leading-relaxed text-slate-600 dark:text-slate-300">Her sektör için tekrar eden sayfalar üretmek yerine, gerçek ihtiyacı ilgili çözüm yaklaşımıyla eşleştiriyoruz.</p></div><div className="mt-8 grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-3">{sectors.map(([name,example],index) => { const Icon=[Factory,ShoppingCart,Truck,Wrench][index%4]; const solution=businessSolutions[index%businessSolutions.length]; return <Link key={name} href={`/cozumler/${solution.slug}`} className="min-w-0 rounded-2xl border border-slate-200 bg-slate-50 p-5 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:border-slate-700 dark:bg-slate-950"><Icon size={20} className="text-[#B83A12] dark:text-orange-300" aria-hidden="true" /><h3 className="mt-3 font-black text-slate-950 dark:text-white">{name}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{example}</p></Link>; })}</div></div></section>
        <section><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Teknik hizmetler</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">Çözümü hayata geçiren kurumsal hizmetler</h2></div><div className="mt-8 grid min-w-0 gap-4 md:grid-cols-2 lg:grid-cols-3">{corporateServices.map(service => <Link key={service.slug} href={`/kurumsal/${service.slug}`} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:border-slate-700 dark:bg-slate-900"><h3 className="font-bold text-slate-950 dark:text-white">{service.shortTitle}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{service.shortDescription}</p></Link>)}</div></div></section>
        <section className="border-t border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-10 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Araştırma merkezi</p><h2 className="mt-2 text-2xl font-black text-slate-950 dark:text-white">Çözüm seçmeden önce karar ölçütlerini inceleyin</h2><p className="mt-2 max-w-3xl text-slate-600 dark:text-slate-300">Hazır ürün, özel geliştirme, maliyet kapsamı ve dijital geçiş risklerini rehberlerle değerlendirin.</p></div><Link href="/kurumsal/rehber" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#B83A12] px-6 py-3 font-bold text-[#B83A12] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:text-orange-300">Karar rehberlerini okuyun <ArrowRight size={18} aria-hidden="true" /></Link></div></section>
        <section className="border-t border-slate-200 bg-orange-50 dark:border-slate-800 dark:bg-orange-950/20"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-10 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Karar desteği</p><h2 className="mt-2 text-2xl font-black text-slate-950 dark:text-white">Hangi kapsamda bir çözüme ihtiyacınız var?</h2><p className="mt-2 max-w-3xl text-slate-600 dark:text-slate-300">Platform, entegrasyon, veri ve kullanıcı yapısını seçerek ön kapsamınızı oluşturun.</p></div><Link href="/kurumsal/yazilim-projesi-kapsam-hesaplama" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#B83A12] px-6 py-3 font-bold text-[#B83A12] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:text-orange-300">Kapsamı Hesapla <ArrowRight size={18} aria-hidden="true" /></Link></div></section>
    </main>;
}
