import type { GoldTypeId } from "@/lib/gold/goldPriceTypes";

export type GoldLongTailSlug =
    | "gram-altin-hesaplama"
    | "ceyrek-altin-hesaplama"
    | "22-ayar-bilezik-hesaplama"
    | "altin-bozdurma-hesaplama"
    | "tl-altin-hesaplama"
    | "14-ayar-altin-hesaplama"
    | "18-ayar-altin-hesaplama";

export type GoldLongTailMode = "altindan-tlye" | "tlden-altina" | "bozdurma";

export type GoldLongTailPageConfig = {
    slug: GoldLongTailSlug;
    title: string;
    metaDescription: string;
    h1: string;
    intro: string;
    targetQueries: string[];
    goldType: GoldTypeId;
    mode: GoldLongTailMode;
    amount: number;
    content: Array<{ title: string; body: string; links?: Array<{ label: string; href: string }> }>;
    faq: Array<{ question: string; answer: string }>;
};

export const GOLD_LONG_TAIL_PAGES: Record<GoldLongTailSlug, GoldLongTailPageConfig> = {
    "gram-altin-hesaplama": {
        slug: "gram-altin-hesaplama",
        title: "Gram Altın Hesaplama 2026 - 1, 10 ve 100 Gram Altın Kaç TL?",
        metaDescription: "Canlı gram altın alış/satış fiyatıyla 1 gram, 10 gram ve 100 gram altının TL karşılığını hesaplayın. TL'den gram altına dönüşümü görün.",
        h1: "Gram Altın Hesaplama - 1, 10 ve 100 Gram Altın Kaç TL?",
        intro: "24 ayar gram altın satış fiyatıyla altından TL'ye veya TL'den gram altına hızlı dönüşüm yapın.",
        targetQueries: ["gram altın hesaplama", "1 gram altın kaç TL", "10 gram altın kaç TL", "100 gram altın kaç TL"],
        goldType: "gram24k",
        mode: "altindan-tlye",
        amount: 10,
        content: [
            { title: "Gram altın nasıl hesaplanır?", body: "Gram altın değeri, girilen gram miktarının güncel 24 ayar gram altın fiyatıyla çarpılmasıyla bulunur. Alım için satış fiyatı, bozdurma için alış fiyatı esas alınır." },
            { title: "Gram altın fiyatı nasıl belirlenir?", body: "Gram altın fiyatı serbestçe belirlenen bir rakam değildir; uluslararası ons altın fiyatı ile dolar/TL kurundan türetilir. Ons, yaklaşık 31,1035 grama karşılık gelen uluslararası ağırlık birimidir ve altın dünya piyasalarında dolar cinsinden ons üzerinden işlem görür. Buna göre yaklaşık gram fiyatı, ons fiyatının dolar kuruyla çarpılıp 31,1035'e bölünmesiyle bulunur. Bu iki değişken nedeniyle ons altın sabit kalsa bile dolar kuru yükseldiğinde TL bazlı gram altın fiyatı artar; tersi durumda geriler. Buradaki tablolarda gösterilen fiyat 24 ayar, yani has altın fiyatıdır. 22 ayar bilezik gibi takı ürünlerinde her gramda yaklaşık 0,917 gram has altın bulunduğu için birim fiyat gram altının altında kalır." },
            { title: "Gram altın nasıl hesaplanır? (Örnek)", body: "Diyelim ki gram altın alış fiyatı 5.000 TL, satış fiyatı 5.075 TL olsun. 10 gram altın almak isteyen biri satış fiyatını esas alır: 10 × 5.075 = 50.750 TL öder. Aynı kişi elindeki 10 gramı aynı anda bozdurmak isteseydi alış fiyatı geçerli olacak ve 10 × 5.000 = 50.000 TL alacaktı. Aradaki 750 TL, alış ile satış arasındaki makastır ve işlemin maliyetidir. Bu nedenle kısa vadeli alıp satmalarda makas doğrudan zarar olarak görünür; altının makası aşacak kadar değer kazanması gerekir. Buradaki fiyatlar yalnızca örnek amaçlıdır, güncel tutarlar sayfadaki canlı tabloda yer alır." },
            { title: "Gram altın alırken nelere dikkat edilir?", body: "Fiziki gram altın alırken ürünün üzerindeki ayar damgası, gramaj ve üretici firma bilgisi kontrol edilmelidir. Külçe ve gram altınlarda ambalajın açılmamış olması, üzerindeki seri numarasının okunabilir durumda bulunması önemlidir; ambalajı bozulmuş ürünlerde bozdurma sırasında değer kaybı yaşanabilir. Kuyumcu ve banka fiyatları farklılık gösterebilir: bankalar genellikle daha dar makas uygularken kuyumcularda fiziki teslim ve ürün primi öne çıkar. Takı ürünlerinde ise işçilik veya milyem bedeli satış fiyatına eklenir ve bu bedel bozdurma sırasında çoğu zaman tam olarak geri alınamaz. Bu yüzden yatırım amaçlı alımlarda işçilik payı düşük ürünler tercih edilir." },
            {
                title: "Gram altın mı çeyrek altın mı?",
                body: "Gram altının en belirgin avantajı bölünebilirliğidir: istediğiniz gramajda alabilir, birikiminizin yalnızca bir kısmını bozdurabilirsiniz. Çeyrek altın ise bütün bir üründür ve bozdurmak istediğinizde tamamını elden çıkarmanız gerekir. Buna karşılık çeyrek altın, hediye ve düğün geleneği nedeniyle Türkiye'de daha likit sayılır ve alıcı bulmak kolaydır. Fiyatlama açısından çeyrek altında ürün primi bulunur; yaklaşık 1,604 gram has altın içermesine rağmen fiyatı bu gram karşılığının bir miktar üzerindedir. Yatırım amacıyla saf altın değeri hedefleniyorsa gram altın genellikle daha verimlidir; hediye amacı öndeyse çeyrek öne çıkar.",
                links: [
                    { label: "Çeyrek altın hesaplama", href: "/finansal-hesaplamalar/ceyrek-altin-hesaplama" },
                    { label: "TL'den altına hesaplama", href: "/finansal-hesaplamalar/tl-altin-hesaplama" },
                    { label: "Altın bozdurma hesaplama", href: "/finansal-hesaplamalar/altin-bozdurma-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "1 gram altın kaç TL?", answer: "1 gram altının TL karşılığı sabit değildir; ons altın fiyatı ve dolar/TL kuru gün içinde değiştikçe fiyat da anlık olarak hareket eder. Bu sayfadaki tabloda son bilinen alış ve satış fiyatı gösterilir. Alım yapacaksanız satış, bozdurma yapacaksanız alış fiyatı sizin için geçerli olan rakamdır." },
            { question: "Gram altın 24 ayar mıdır?", answer: "Evet, gram altın olarak fiyatlanan ürün 24 ayar, yani has altındır ve saflığı binde 995 ile 999 arasındadır. 22 ayar bilezikte her gram yaklaşık 0,917 gram, 18 ayarda 0,750 gram, 14 ayarda ise yaklaşık 0,583 gram has altın bulunur. Bu nedenle takı ürünlerinin gram fiyatı 24 ayar gram altın fiyatının altındadır." },
            { question: "Gram altın nasıl bozdurulur, kayıp olur mu?", answer: "Gram altın kuyumcu veya bankada, işlem anındaki alış fiyatı üzerinden bozdurulur. Kayıp iki kalemden doğar: alış ile satış arasındaki makas ve varsa ürüne ödenmiş işçilik bedeli. Ambalajı açılmamış, seri numarası okunabilir külçe ve gram altınlarda değer kaybı en düşük düzeydedir; ambalajı bozulmuş veya ayarı belirsiz ürünlerde kuyumcu ek kontrol nedeniyle daha düşük fiyat verebilir." },
            { question: "Gram altın mı çeyrek altın mı daha mantıklı?", answer: "Yatırım amacı öndeyse gram altın genellikle daha verimlidir: istediğiniz miktarda alınabilir, kısmi bozdurmaya izin verir ve çeyrekteki ürün primini içermez. Çeyrek altın ise yaklaşık 1,604 gram has altın içerir ancak fiyatında bir prim taşır; buna karşılık hediye geleneği nedeniyle çok likittir. Kısacası saf altın değeri hedefleniyorsa gram, hediye veya kolay elden çıkarma öncelikliyse çeyrek öne çıkar." },
            { question: "Gram altın fiyatı neye göre değişir?", answer: "Gram altın fiyatı iki temel değişkene bağlıdır: uluslararası ons altın fiyatı ve dolar/TL kuru. Ons fiyatı küresel faiz beklentileri, enflasyon verileri, merkez bankası alımları ve jeopolitik gelişmelerle hareket eder. Dolar kuru ise TL tarafındaki fiyatı doğrudan etkiler; ons sabit kalsa bile kur yükseldiğinde gram altın TL bazında pahalanır. Ayrıca iç piyasadaki arz-talep dengesi ve kurum makası günlük fiyatta küçük farklar yaratabilir." },
        ],
    },
    "ceyrek-altin-hesaplama": {
        slug: "ceyrek-altin-hesaplama",
        title: "Çeyrek Altın Hesaplama 2026 - Çeyrek Altın Kaç TL?",
        metaDescription: "Canlı çeyrek altın alış/satış fiyatıyla 1, 5 ve 10 çeyrek altının TL karşılığını hesaplayın. Çeyrek kaç gram, ürün primi ve bozdurma farkı örnekle.",
        h1: "Çeyrek Altın Hesaplama - Çeyrek Altın Kaç TL?",
        intro: "Çeyrek altının son bilinen alış/satış fiyatıyla adet bazlı TL karşılığını hesaplayın.",
        targetQueries: ["çeyrek altın hesaplama", "çeyrek altın kaç TL", "1 çeyrek altın kaç TL", "10 çeyrek altın kaç TL"],
        goldType: "ceyrek",
        mode: "altindan-tlye",
        amount: 1,
        content: [
            { title: "Çeyrek altın hesabı neden farklıdır?", body: "Çeyrek altın yaklaşık 1,604 gram has altın içerir. Piyasa primi ve alış-satış makası nedeniyle fiyatı yalnız gram ağırlığıyla birebir hesaplanmaz." },
            { title: "Çeyrek altın kaç gramdır, fiyatı nasıl belirlenir?", body: "Çeyrek altının toplam ağırlığı yaklaşık 1,754 gramdır ve 22 ayar olarak basılır. 22 ayarda saflık binde 916-917 düzeyinde olduğundan, bu ağırlığın yaklaşık 1,604 gramı has altına karşılık gelir; kalan kısım alaşımdır. Fiyatın çıkış noktası bu has altın miktarıdır: 24 ayar gram altın fiyatı 1,604 ile çarpıldığında çeyreğin içindeki saf altının değeri bulunur. Ancak piyasadaki çeyrek fiyatı bu rakamın bir miktar üzerindedir, çünkü basım, işçilik ve dağıtım maliyetlerini yansıtan bir ürün primi eklenir. Talebin arttığı dönemlerde bu prim genişleyebilir, durgun dönemlerde daralır. Eski ve yeni çeyrek ayrımı da fiyata yansır: Cumhuriyet dönemi öncesi ve sonrası basımlar arasında ağırlık ile ayar bakımından küçük farklar bulunabildiği için kuyumcular eski çeyreklerde farklı fiyat verebilir." },
            { title: "Çeyrek altın nasıl hesaplanır? (Örnek)", body: "Çeyrek altın adet üzerinden hesaplanır, gram girmeye gerek yoktur. Diyelim ki çeyrek altın alış fiyatı 8.400 TL, satış fiyatı 8.650 TL olsun. 5 çeyrek altın almak isteyen biri satış fiyatını esas alır: 5 × 8.650 = 43.250 TL öder. Aynı kişi bu 5 çeyreği aynı gün bozdurmak isteseydi alış fiyatı geçerli olacak ve 5 × 8.400 = 42.000 TL alacaktı. Aradaki 1.250 TL, adet başına 250 TL'lik alış-satış makasının toplamıdır ve işlemin maliyetini gösterir. Bu nedenle çeyrek altında kısa vadeli alıp satmak, makas kapanana kadar zarar yazmak anlamına gelir. Buradaki rakamlar yalnızca örnektir; güncel alış ve satış fiyatları sayfadaki canlı tabloda yer alır." },
            { title: "Çeyrek altın alırken ve bozdururken dikkat", body: "Çeyrek altın alırken ürünün darphane basımı mı yoksa kuyumcu basımı mı olduğu kontrol edilmelidir. Darphane basımı ürünler standart ağırlık ve ayarda olduğu için bozdurmada sorunsuz kabul görür; kuyumcu basımlarında ise ağırlık ve ayar farkı nedeniyle alış fiyatı bir miktar düşük kalabilir. Ambalajlı ve tırtıklı kenar yapısı bozulmamış çeyrekler daha yüksek fiyatla işlem görür; delinmiş, lehimlenmiş veya kolye ucu olarak kullanılmış çeyrekler ziynet değeri kaybettiği için düşük fiyatlanır. Alım sırasında ödenen ürün primi bozdurma sırasında geri alınamaz, çünkü kuyumcu ürünü genellikle has altın değerine yakın bir fiyattan devralır. Düğün ve bayram gibi talebin yükseldiği dönemlerde çeyreğin primi genişleyebilir; bu dönemlerde alım yapmak maliyeti artırır, bozdurmak ise görece avantajlı olabilir." },
            {
                title: "Çeyrek mi gram mı?",
                body: "Çeyrek altının en güçlü tarafı hediyelik değeri ve likiditesidir. Düğün, sünnet ve doğum geleneği nedeniyle Türkiye'de çeyreğin alıcısı her zaman vardır ve elden çıkarmak kolaydır. Buna karşılık çeyrekte ürün primi gram altına göre belirgin biçimde yüksektir: aynı tutara denk gelen saf altın miktarı gram altında daha fazladır. Bir diğer fark bölünebilirliktir; çeyrek bütün bir üründür, ihtiyaç halinde yarısını bozduramaz, tamamını elden çıkarmanız gerekir. Gram altında ise birikiminizin yalnızca bir kısmını nakde çevirebilirsiniz. Bu nedenle yatırım amacı öndeyse ve saf altın değeri hedefleniyorsa gram altın genellikle daha verimlidir; hediye etme veya hızlı elden çıkarma önceliğiniz varsa çeyrek altın öne çıkar.",
                links: [
                    { label: "Gram altın hesaplama", href: "/finansal-hesaplamalar/gram-altin-hesaplama" },
                    { label: "TL'den altına hesaplama", href: "/finansal-hesaplamalar/tl-altin-hesaplama" },
                    { label: "Altın bozdurma hesaplama", href: "/finansal-hesaplamalar/altin-bozdurma-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "Çeyrek altın kaç TL?", answer: "Çeyrek altının TL karşılığı sabit değildir; ons altın fiyatı ve dolar/TL kuru gün içinde hareket ettikçe çeyrek fiyatı da değişir. Buna ek olarak çeyreğin içerdiği ürün primi talebe göre genişleyip daralabilir. Bu sayfadaki tabloda son bilinen alış ve satış fiyatı gösterilir; alım yapacaksanız satış, bozdurma yapacaksanız alış fiyatı sizin için geçerli olan rakamdır." },
            { question: "Çeyrek altın kaç gramdır?", answer: "Çeyrek altının toplam ağırlığı yaklaşık 1,754 gramdır ve 22 ayar olarak basılır. 22 ayarda saflık binde 916-917 düzeyinde olduğu için bu ağırlığın yaklaşık 1,604 gramı has altına karşılık gelir, kalan kısım ise dayanıklılığı artıran alaşımdır. Fiyat hesabında esas alınan miktar bu 1,604 gramlık has altın içeriğidir." },
            { question: "Eski çeyrek ile yeni çeyrek farkı nedir?", answer: "Halk arasında eski çeyrek denilen Cumhuriyet öncesi ve erken dönem basımlar ile güncel darphane basımları arasında ağırlık ve ayar bakımından küçük farklar bulunabilir. Bu nedenle kuyumcular eski çeyreklere farklı, çoğu zaman biraz daha düşük bir alış fiyatı uygulayabilir. Yeni basım darphane çeyrekleri standart ağırlık ve ayarda olduğu için bozdurmada tereddütsüz kabul görür. Koleksiyon değeri taşıyan bazı eski basımlar ise altın değerinin üzerinde fiyatlanabilir." },
            { question: "Çeyrek altın bozdurulunca kayıp olur mu?", answer: "Evet, iki kalemde kayıp oluşur. Birincisi alış ile satış fiyatı arasındaki makastır. İkincisi ve daha belirleyici olanı, alım sırasında ödenen ürün primidir: çeyreğin basım ve işçilik maliyetini yansıtan bu fark bozdurmada geri alınamaz, çünkü kuyumcu ürünü has altın değerine yakın bir fiyattan devralır. Ambalajı bozulmamış darphane basımı çeyreklerde kayıp en düşük düzeydedir; delinmiş veya takı olarak kullanılmış çeyreklerde kayıp belirgin biçimde artar." },
            { question: "Çeyrek altın mı gram altın mı daha avantajlı?", answer: "Yatırım amacı öndeyse gram altın genellikle daha avantajlıdır, çünkü ürün primi düşüktür ve aynı tutara daha fazla saf altın alınır; ayrıca kısmi bozdurmaya izin verir. Çeyrek altın ise hediye geleneği nedeniyle çok likittir ve alıcı bulmak kolaydır, ancak primi yüksektir ve bütün olarak elden çıkarılması gerekir. Kısacası saf altın biriktirmek istiyorsanız gram, hediye veya hızlı nakde çevirme önceliğinizse çeyrek öne çıkar." },
        ],
    },
    "22-ayar-bilezik-hesaplama": {
        slug: "22-ayar-bilezik-hesaplama",
        title: "22 Ayar Bilezik Hesaplama 2026 - Bilezik Bozdurma Değeri",
        metaDescription: "22 ayar bilezik gramını canlı altın fiyatıyla hesaplayın. 916 milyem has karşılığı, işçilik farkı ve bozdurma değeri örnekle anlatılıyor.",
        h1: "22 Ayar Bilezik Hesaplama - Bilezik Bozdurma Değeri",
        intro: "22 ayar bilezikte gram miktarını 0,917 has altın oranıyla değerlendirerek yaklaşık TL karşılığını görün.",
        targetQueries: ["22 ayar bilezik hesaplama", "22 ayar bilezik bozdurma hesaplama", "10 gram 22 ayar bilezik kaç TL"],
        goldType: "gram22k",
        mode: "bozdurma",
        amount: 10,
        content: [
            { title: "22 ayar bilezik nasıl hesaplanır?", body: "Yaklaşık formül gram miktarı x 24 ayar gram fiyatı x 0,917 şeklindedir. Bozdurma tarafında alış fiyatı kullanılır." },
            { title: "22 ayar bilezik kaç ayar, milyemi nedir?", body: "22 ayar, bin birim alaşımda 916 birim saf altın bulunduğu anlamına gelir; bu orana milyem denir ve pratikte 0,916 ile 0,917 arasında kabul edilir. Geriye kalan yaklaşık 84 birim gümüş ve bakır gibi alaşım metallerinden oluşur. Bilezik ve geleneksel ziynet takılarında 22 ayarın standart haline gelmesinin nedeni saflık ile dayanıklılık arasındaki dengedir: 24 ayar saf altın çok yumuşak olduğu için günlük kullanımda kolayca ezilir ve şeklini kaybeder, buna karşılık 22 ayar alaşım hem yüksek altın oranını korur hem de bilezik gibi sürekli takılan bir ürünün aşınmasına dayanır. Ayrıca yüksek has oranı, ürünün gerektiğinde kolayca nakde çevrilebilmesini sağlar. Bu yüzden 22 ayar bilezik Türkiye'de hem takı hem de birikim aracı olarak görülür." },
            { title: "22 ayar bilezik hesaplama (Örnek)", body: "15 gram ağırlığında bir 22 ayar bileziği ele alalım ve gram has altın alış fiyatının 5.000 TL olduğunu varsayalım. Önce has altın karşılığı bulunur: 15 × 0,916 = 13,74 gram saf altın. Ardından bu miktar alış fiyatıyla değerlendirilir: 13,74 × 5.000 = 68.700 TL. Bozdurmada eline geçen tutar bu civarda olur. Aynı bileziği satın alırken ise durum farklıdır: satış fiyatı üzerinden hesaplanan has değere ek olarak gram başına işçilik bedeli ödenir. İşçiliğin gram başına 400 TL olduğu bir senaryoda yalnızca işçilik kalemi 15 × 400 = 6.000 TL tutar ve bu tutar bozdurmada geri alınamaz. Alım ile bozdurma arasındaki fark büyük ölçüde buradan doğar. Rakamlar yalnızca örnektir; güncel fiyatlar sayfadaki canlı tabloda yer alır." },
            { title: "Bilezik alırken ve bozdururken", body: "Bilezikte işçilik payı, altın ürünleri arasında en yüksek gruplardandır; burma, kelepçe ve ajur gibi işlemeli modellerde bu pay daha da artar. Sade ve düz modellerde işçilik görece düşüktür, bu nedenle birikim amacı öndeyse sade modeller tercih edilir. Alım sırasında bileziğin gramajının önünüzde tartılması ve ayar damgasının kontrol edilmesi önemlidir; kuyumcu genellikle ayarı ölçüm cihazıyla doğrular. Düğün, bayram ve kına sezonu gibi talebin yükseldiği dönemlerde bilezik işçiliği ve ürün primi genişleyebilir; bu dönemlerde alım yapmak maliyeti artırırken, elindekini bozdurmak isteyen için koşullar görece elverişli olabilir. Bozdurmada belirleyici olan işçilik değil, bileziğin içerdiği has altın miktarıdır." },
            {
                title: "Bilezik ekonomisi ve düğün geleneği",
                body: "Türkiye'de bilezik, yalnızca bir takı değil, kuşaklar arası aktarılan bir birikim aracıdır. Düğünlerde takılan bilezikler geleneksel olarak yeni kurulan aileye bir başlangıç sermayesi işlevi görür; nakit yerine altın verilmesinin nedeni, altının enflasyon karşısında satın alma gücünü koruma beklentisidir. Bu ikili kullanım bileziğe kendine özgü bir ekonomi kazandırır: ürün hem takılabilir hem de ihtiyaç anında hızlıca nakde çevrilebilir. Bilezik ayrıca bölünebilir bir birikimdir; birden fazla bileziği olan biri yalnızca birini bozdurup gerisini elinde tutabilir. Buna karşılık her bozdurmada işçilik kaybı yeniden gündeme gelir. Yatırım amacı tek başına öndeyse gram altın veya külçe daha verimli olabilir; hediyelik değer ve kullanım da isteniyorsa bilezik bu iki ihtiyacı birleştirir.",
                links: [
                    { label: "Altın bozdurma hesaplama", href: "/finansal-hesaplamalar/altin-bozdurma-hesaplama" },
                    { label: "Gram altın hesaplama", href: "/finansal-hesaplamalar/gram-altin-hesaplama" },
                    { label: "Çeyrek altın hesaplama", href: "/finansal-hesaplamalar/ceyrek-altin-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "22 ayar kaç milyemdir?", answer: "22 ayar 916 milyeme karşılık gelir; yani bin birim alaşımın 916 birimi saf altındır ve pratikte 0,916 ile 0,917 arasında bir oran kullanılır. Kalan kısım gümüş ve bakır gibi alaşım metallerinden oluşur. Karşılaştırma için 24 ayar 995 ve üzeri, 18 ayar 750, 14 ayar ise 583 milyemdir (piyasada 585 damgalı). Bir bileziğin değeri hesaplanırken gram ağırlığı bu milyem oranıyla çarpılarak içerdiği has altın miktarı bulunur." },
            { question: "22 ayar bilezik kaç para eder?", answer: "Bileziğin bozdurma değeri, gram ağırlığının 0,916 ile çarpılıp güncel gram has altın alış fiyatıyla değerlendirilmesiyle bulunur. Örneğin 15 gramlık bir bilezik yaklaşık 13,74 gram saf altın içerir. Kesin tutar, o anki altın fiyatına ve kuyumcunun uyguladığı işlem payına göre değişir. Alım fiyatı ise bundan daha yüksektir, çünkü satış fiyatı esas alınır ve üzerine işçilik bedeli eklenir." },
            { question: "Bilezikte işçilik geri alınır mı?", answer: "Kural olarak hayır. Bilezik alırken ödenen işçilik bedeli, bozdurma sırasında geri alınamaz; kuyumcu ürünü içerdiği has altın değerine yakın bir fiyattan devralır, çünkü ürün eritilip yeniden işlenecektir. İşçilik payı bilezikte altın ürünleri arasında en yüksek gruplardandır ve burma ile ajur gibi işlemeli modellerde daha da artar. Birikim amacı öndeyse sade modeller tercih edilir, çünkü ödenen ve geri alınamayan işçilik daha düşük olur." },
            { question: "22 ayar bilezik mi 14 ayar bilezik mi?", answer: "İkisi farklı ihtiyaçlara yanıt verir. 22 ayar 916 milyemle çok daha yüksek has altın içerir, bu nedenle bozdurmada belirgin biçimde daha fazla değer taşır ve birikim amacına uygundur. 14 ayar ise 583 milyemle (piyasada 585 damgalı) daha az altın içerir, buna karşılık sert alaşımı sayesinde günlük yoğun kullanımda daha dayanıklıdır ve alım maliyeti düşüktür. Türkiye'de geleneksel bilezik ve düğün takısında 22 ayar standarttır; 14 ayar daha çok günlük kullanım takılarında tercih edilir." },
            { question: "Düğünde takılan altının değeri nasıl hesaplanır?", answer: "Düğünde takılan bilezikler için hesap diğer 22 ayar ürünlerle aynıdır: toplam gram ağırlık 0,916 ile çarpılır ve çıkan has altın miktarı güncel gram alış fiyatıyla değerlendirilir. Bilezik yanında çeyrek, yarım veya tam altın takıldıysa bunlar adet üzerinden ayrı hesaplanır, çünkü basılı ürünlerde ayrıca bir ürün primi bulunur. Toplam değeri görmek için her ürün türünü kendi hesabıyla değerlendirip toplamak gerekir." },
        ],
    },
    "altin-bozdurma-hesaplama": {
        slug: "altin-bozdurma-hesaplama",
        title: "Altın Bozdurma Hesaplama 2026 - Kuyumcu Alış Fiyatı",
        metaDescription: "Gram, çeyrek, bilezik ve ziynet altını bozdururken eline geçecek tutarı alış fiyatıyla hesaplayın. Has altın formülü, kayıp kalemleri ve örnek hesap.",
        h1: "Altın Bozdurma Hesaplama - Kuyumcu Alış Fiyatı",
        intro: "Altın satarken veya bozdururken alış fiyatı baz alınır. Seçtiğiniz ürün için yaklaşık bozdurma değerini hesaplayın.",
        targetQueries: ["altın bozdurma hesaplama", "kuyumcu altın bozdurma hesaplama", "altın satarken hangi fiyat kullanılır"],
        goldType: "gram24k",
        mode: "bozdurma",
        amount: 10,
        content: [
            { title: "Altın bozdurma hesabı nasıl yapılır?", body: "Seçilen altın türünün miktarı güncel alış fiyatıyla çarpılır. Alış fiyatı kurumun kullanıcıdan altını aldığı fiyattır." },
            { title: "Bozdurma hesabında has altın mantığı", body: "Ayarı ne olursa olsun her altın ürünün bozdurma değeri, içerdiği saf altın miktarı üzerinden bulunur. Formül üç adımdan oluşur: ürünün gram ağırlığı, ayarına karşılık gelen milyem oranıyla çarpılır ve çıkan has altın miktarı güncel gram has altın alış fiyatıyla değerlendirilir. Milyem, bin birim alaşımda kaç birim saf altın bulunduğunu gösterir: 14 ayar 583 (piyasada 585 damgalı), 18 ayar 750, 22 ayar 916, 24 ayar ise 995 ve üzeri milyeme karşılık gelir. Bu yüzden 10 gramlık bir 14 ayar ürün ile 10 gramlık bir 22 ayar ürün aynı ağırlıkta olmalarına rağmen çok farklı tutarlara bozdurulur; belirleyici olan ağırlık değil, içindeki has altındır. Aynı formül bilezikten künyeye, yüzükten külçeye kadar tüm ürünlerde geçerlidir. Ayarlara özel ayrıntılar ve her ayarın kendi hesap örneği için ilgili ayar sayfalarına bakabilirsiniz." },
            { title: "Bozdurma örneği", body: "20 gram ağırlığında 22 ayar bir bileziği ele alalım ve gram has altın alış fiyatının 5.000 TL olduğunu varsayalım. İlk adımda has altın miktarı bulunur: 20 × 0,916 = 18,32 gram saf altın. İkinci adımda bu miktar alış fiyatıyla değerlendirilir: 18,32 × 5.000 = 91.600 TL. Kuyumcunun uyguladığı fiyat çoğu zaman bu teorik has değerin bir miktar altında kalır; örneğin yüzde iki düzeyinde bir fark uygulandığında elinize geçen tutar yaklaşık 89.770 TL olur. Aradaki fark kuyumcunun işlem payı ve eritme riskini karşılar. Aynı bileziği alırken satış fiyatı ve üzerine işçilik ödemiş olduğunuzu düşünürseniz, alım ile bozdurma arasındaki toplam fark daha da belirginleşir. Buradaki rakamlar yalnızca örnektir; güncel fiyatlar sayfadaki canlı tabloda yer alır." },
            { title: "Bozdururken ne kadar kayıp olur?", body: "Kayıp tek bir kalemden değil, üst üste binen birkaç kalemden doğar. Birincisi alış ile satış arasındaki makastır: kurum size sattığı fiyattan değil, daha düşük olan alış fiyatından geri alır. İkincisi ürün primi ve işçiliktir; basılı ziynet ürünlerinde basım payı, takılarda ise işçilik bedeli alım sırasında ödenir ancak bozdurmada geri alınmaz, çünkü ürün çoğunlukla has altın değeri üzerinden devralınır. Üçüncüsü milyem eksiğidir: bazı takılarda gerçek ayar, damgada yazandan bir miktar düşük çıkabilir ve kuyumcu ölçüm sonucuna göre fiyat verir. Dördüncüsü lehim ve montür kaybıdır; kolye kilidi, yüzük taşı yuvası ve lehimli birleşim noktaları saf altın sayılmaz ve tartıdan düşülebilir. Bu nedenle darphane basımı ambalajlı ürünlerde kayıp en düşük, işçiliği ağır takılarda ise en yüksek düzeydedir." },
            {
                title: "Nerede bozdurmalı?",
                body: "Kuyumcular fiziki altında en yaygın adrestir; işlem hızlıdır ve ürün çeşidi fark etmeksizin kabul edilir, ancak fiyat kurumdan kuruma değişebildiği için birkaç yerden teklif almak farkı görmenizi sağlar. Bankalar genellikle daha dar makas uygular ve fiyatlaması şeffaftır, fakat çoğunlukla kendi sattıkları standart ürünleri veya altın hesabındaki bakiyeyi işleme alır; her tür takıyı kabul etmeyebilirler. Kapalıçarşı gibi toptancı yoğunluklu merkezlerde rekabet nedeniyle fiyatlar rakip kalabilir. Nerede işlem yaparsanız yapın, tartının önünüzde yapılması, ayar ölçümünün nasıl belirlendiğinin açıklanması ve verilen fiyatın hangi gram has altın fiyatına dayandığının söylenmesi şeffaflık açısından önemlidir. Altın fiyatı gün içinde hareket ettiği için kurumlar genellikle işlem anındaki fiyatı esas alır; teklif aldıktan sonra beklerseniz fiyat değişebilir.",
                links: [
                    { label: "22 ayar bilezik hesaplama", href: "/finansal-hesaplamalar/22-ayar-bilezik-hesaplama" },
                    { label: "Gram altın hesaplama", href: "/finansal-hesaplamalar/gram-altin-hesaplama" },
                    { label: "Çeyrek altın hesaplama", href: "/finansal-hesaplamalar/ceyrek-altin-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "Altın bozdurunca ne kadar kayıp olur?", answer: "Kayıp ürün türüne göre değişir ve birkaç kalemden oluşur: alış-satış makası, alım sırasında ödenmiş ürün primi veya işçilik, varsa milyem eksiği ve lehim gibi saf altın sayılmayan kısımlar. Darphane basımı, ambalajı açılmamış külçe ve gram altınlarda kayıp en düşük düzeydedir. İşçiliği ağır bilezik, kolye ve yüzük gibi takılarda ise kayıp belirgin biçimde artar, çünkü bu ürünler genellikle yalnızca içerdikleri has altın değeri üzerinden devralınır." },
            { question: "Bozdurma fiyatı neye göre belirlenir?", answer: "Belirleyici olan ürünün ağırlığı değil, içerdiği has altın miktarıdır. Gram ağırlık, ayarın milyem oranıyla çarpılarak saf altın karşılığı bulunur ve bu miktar güncel gram has altın alış fiyatıyla değerlendirilir. Alış fiyatı, kurumun sizden altını devraldığı fiyattır ve satış fiyatının altındadır. Buna ek olarak kuyumcu kendi işlem payını ve eritme riskini yansıtan küçük bir fark uygulayabilir." },
            { question: "İşçilik veya ürün primi geri alınır mı?", answer: "Kural olarak hayır. Takı alırken ödenen işçilik bedeli ile çeyrek, yarım ve tam altın gibi basılı ürünlerde ödenen basım primi, bozdurma sırasında geri alınamaz. Kuyumcu ürünü çoğunlukla içerdiği has altın değerine yakın bir fiyattan devralır, çünkü ürünü eritip yeniden işleyecektir. Bu nedenle yatırım amaçlı alımlarda primi ve işçiliği düşük ürünler tercih edilir; ziynet ve takı ürünleri ise daha çok kullanım ve hediye amacı taşır." },
            { question: "Nerede bozdurmak daha avantajlı?", answer: "Tek bir adres her durumda avantajlı değildir. Bankalar genellikle daha dar makas ve şeffaf fiyatlama sunar, ancak çoğunlukla standart ürünleri veya altın hesabı bakiyesini işleme alır ve her takıyı kabul etmeyebilir. Kuyumcular ürün çeşidi fark etmeksizin işlem yapar ve hızlıdır, fiyat ise kurumdan kuruma değişir. Toptancı yoğunluklu merkezlerde rekabet fiyatı olumlu etkileyebilir. Genel olarak birkaç yerden teklif almak, tartının önünüzde yapılmasını istemek ve fiyatın hangi gram has altın değerine dayandığını sormak farkı görmenizi sağlar." },
            { question: "Bilezik veya ziynet bozdurmak farklı mı?", answer: "Hesabın mantığı aynıdır: ağırlık, milyem oranıyla çarpılıp has altın karşılığı bulunur. Fark sonuçta ortaya çıkar. Takı ürünlerinde alım sırasında ödenen işçilik bozdurmada karşılık bulmaz; ayrıca kolye kilidi, yüzük taşı yuvası ve lehimli birleşim noktaları saf altın sayılmadığı için tartıdan düşülebilir. Bazı takılarda gerçek ayar damgada yazandan düşük çıkabilir ve fiyat ölçüm sonucuna göre verilir. Bu nedenle ziynet ürünlerinde eline geçen tutar, aynı gramajdaki külçe veya gram altına göre daha düşük olur." },
        ],
    },
    "tl-altin-hesaplama": {
        slug: "tl-altin-hesaplama",
        title: "TL'den Altına Hesaplama 2026 - 10000 TL Kaç Gram Altın?",
        metaDescription: "TL tutarınızı canlı gram altın satış fiyatına bölerek kaç gram altın alınabileceğini hesaplayın. 1000, 10000 ve 100000 TL senaryoları.",
        h1: "TL'den Altına Hesaplama - 10000 TL Kaç Gram Altın?",
        intro: "TL tutarınızı güncel satış fiyatına bölerek yaklaşık kaç gram altın alınabileceğini görün.",
        targetQueries: ["TL'den altına hesaplama", "1000 TL kaç gram altın", "10000 TL kaç gram altın", "100000 TL kaç gram altın"],
        goldType: "gram24k",
        mode: "tlden-altina",
        amount: 10000,
        content: [
            { title: "TL'den gram altına dönüşüm", body: "Alınabilecek gram = TL tutarı / güncel satış fiyatı formülüyle hesaplanır. Alım senaryosunda satış fiyatı kullanılır." },
            { title: "Elimdeki TL ile kaç gram altın alabilirim?", body: "Hesabın mantığı basit bir bölme işlemidir: elinizdeki TL tutarını gram altının güncel satış fiyatına bölersiniz. Buradaki kritik ayrıntı, alış değil satış fiyatının kullanılmasıdır. Alış ve satış, işlemin sizin değil kurumun tarafından adlandırılır: kuyumcu veya banka altını size satarken satış fiyatını uygular, sizden geri alırken alış fiyatını. Siz altın aldığınız için kurumun satış fiyatı geçerlidir ve bu her zaman alış fiyatının üzerindedir. Aradaki fark olan makas, aynı tutarla alabileceğiniz altın miktarını doğrudan azaltır: satış fiyatı ne kadar yüksekse eldeki TL o kadar az grama denk gelir. Bu nedenle farklı kurumların satış fiyatlarını karşılaştırmak, aynı parayla daha fazla gram almanın en pratik yoludur." },
            { title: "TL'den altına çevirme (Örnek)", body: "Gram altın satış fiyatının 5.075 TL, çeyrek altın satış fiyatının ise 8.650 TL olduğu bir anı ele alalım. Elinde 50.000 TL olan biri gram altına geçmek isterse: 50.000 / 5.075 = yaklaşık 9,85 gram alabilir. Kuyumcular genellikle tam gramajlı ürün sattığı için pratikte 9 gram alınır ve 50.000 - (9 × 5.075) = 4.325 TL nakit olarak elde kalır. Aynı 50.000 TL çeyrek altına yönlendirilseydi: 50.000 / 8.650 = yaklaşık 5,78 çeyrek, yani 5 adet çeyrek alınabilir ve 50.000 - (5 × 8.650) = 6.750 TL artakalır. Görüldüğü gibi gram altın, artan bakiyeyi daha küçük tuttuğu için parayı daha verimli değerlendirir. Buradaki fiyatlar yalnızca örnektir; güncel tutarlar sayfadaki canlı tabloda yer alır." },
            { title: "Ne zaman altına geçmeli?", body: "Bu sorunun tek bir doğru cevabı yoktur ve zamanlama tahmini kimse için garanti değildir. Genel olarak yatırımcıların başvurduğu yaklaşım, tek seferde büyük tutar girmek yerine düzenli aralıklarla küçük alımlar yapmaktır. Maliyet ortalaması denilen bu yöntemde fiyat yüksekken daha az, düşükken daha fazla miktar alınır ve zaman içinde ortalama alım maliyeti tek bir günün fiyatına bağlı kalmaz. Bütçe küçükse gram altın genellikle daha uygundur, çünkü çeyrek gibi bütün ürünlerde asgari tutar daha yüksektir. Ürün seçiminde primi düşük olanlar tercih edilir: yatırım amaçlı alımlarda işçilik payı yüksek takı ürünleri yerine külçe veya gram altın öne çıkar. Bunlar genel bilgilendirmedir; kişisel durumunuza uygun kararı kendi koşullarınıza göre değerlendirmeniz gerekir." },
            {
                title: "TL ile altın alırken dikkat",
                body: "İlk dikkat edilecek nokta makastır: alış ile satış arasındaki fark ne kadar genişse, aldığınız anda üzerinize binen maliyet o kadar yüksektir. Aldığınız altını hemen bozdurmanız gerekirse bu farkı zarar olarak yazarsınız. İkinci nokta ürün primidir; çeyrek, yarım ve tam altın gibi basılı ürünlerde has altın değerinin üzerine basım ve işçilik payı eklenir ve bu pay bozdurmada geri alınamaz. Üçüncüsü ve çoğu zaman gözden kaçanı, küçük gramajlarda prim oranının yükselmesidir: yarım gram veya bir gramlık küçük külçelerde basım maliyeti daha az altına dağıldığı için gram başına ödenen prim, on gramlık bir külçeye göre belirgin biçimde yüksek olur. Aynı tutarla alım yapıyorsanız, mümkün olduğunca büyük gramajlı tek ürün almak genellikle daha verimlidir.",
                links: [
                    { label: "Gram altın hesaplama", href: "/finansal-hesaplamalar/gram-altin-hesaplama" },
                    { label: "Çeyrek altın hesaplama", href: "/finansal-hesaplamalar/ceyrek-altin-hesaplama" },
                    { label: "Altın bozdurma hesaplama", href: "/finansal-hesaplamalar/altin-bozdurma-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "10.000 TL ile kaç gram altın alınır?", answer: "10.000 TL'nin kaç gram altına denk geldiği sabit değildir; gram altının o anki satış fiyatına bölünerek bulunur ve fiyat ons altın ile dolar/TL kuruna bağlı olarak gün içinde hareket eder. Hesap için alış değil satış fiyatı kullanılır, çünkü altını siz alıyorsunuz. Bu sayfadaki tabloda son bilinen satış fiyatı gösterilir; hesaplayıcıya tutarınızı girerek güncel karşılığı görebilirsiniz." },
            { question: "TL'yi altına çevirmek mantıklı mı?", answer: "Bu, kişisel hedeflere ve risk toleransına bağlı bir karardır ve burada yatırım tavsiyesi verilmez. Genel olarak altın, uzun vadede satın alma gücünü korumaya yönelik bir araç olarak görülür; ancak fiyatı ons altın ve dolar kuruna bağlı olarak dalgalanır, kısa vadede değer kaybı da yaşanabilir. Alış-satış makası ve ürün primi nedeniyle kısa vadeli alıp satmalarda maliyet belirgindir. Kararınızı vade beklentiniz ve nakit ihtiyacınızı birlikte değerlendirerek vermeniz uygun olur." },
            { question: "Altın alırken alış mı satış fiyatı geçerli?", answer: "Satış fiyatı geçerlidir. Alış ve satış kavramları kurumun bakış açısıyla adlandırılır: kuyumcu veya banka altını size satarken satış fiyatını, sizden geri alırken alış fiyatını uygular. Dolayısıyla siz altın alırken satış, bozdururken alış fiyatını görürsünüz. Satış fiyatı her zaman alış fiyatının üzerinde olduğu için aynı tutarla alabileceğiniz altın miktarı, makas genişledikçe azalır." },
            { question: "Az parayla altın alınır mı?", answer: "Evet. Gram altının en belirgin avantajı bölünebilirliğidir; yarım gram ve bir gram gibi küçük gramajlı ürünler bulunduğu için düşük bütçeyle de alım yapılabilir. Ayrıca bankaların altın hesapları üzerinden gramın küsuratlı miktarları da alınabilir. Ancak küçük gramajlarda basım maliyeti daha az altına dağıldığından gram başına ödenen prim oranı yükselir. Düzenli küçük alımlar yapılacaksa, biriken tutarla daha büyük gramajlı tek ürüne geçmek genellikle daha verimli olur." },
            { question: "Hangi altın türü daha az prim alır?", answer: "Genel olarak külçe ve gram altın, basılı ziynet ürünlerine göre daha düşük prim taşır; gramaj büyüdükçe gram başına düşen prim de azalır. Çeyrek, yarım ve tam altın gibi ürünlerde basım ve dağıtım maliyetini yansıtan bir prim bulunur ve bu prim bozdurmada geri alınmaz. Bilezik ve kolye gibi takı ürünlerinde ise işçilik bedeli en yüksek düzeydedir; bu ürünler bozdurulurken çoğunlukla has altın değeri üzerinden fiyatlanır. Yatırım amacı öndeyse primi düşük ürünler tercih edilir." },
        ],
    },
    "14-ayar-altin-hesaplama": {
        slug: "14-ayar-altin-hesaplama",
        title: "14 Ayar Altın Hesaplama 2026 - 14 Ayar Altın Kaç TL?",
        metaDescription: "14 ayar altın gramını 0,583 has altın oranıyla hesaplayın. 585 damgası, neden daha ucuz, dayanıklılığı ve bozdurma değeri örnekle.",
        h1: "14 Ayar Altın Hesaplama - 14 Ayar Altın Kaç TL?",
        intro: "14 ayar altında her gramın yaklaşık 0,583 gramı has altındır; ürünler çoğunlukla 585 damgasıyla satılır. Gram miktarına göre yaklaşık değeri hesaplayın.",
        targetQueries: ["14 ayar altın hesaplama", "14 ayar altın bozdurma", "14 ayar altın kaç TL", "14 ayar altın kaç milyem"],
        goldType: "gram14k",
        mode: "bozdurma",
        amount: 10,
        content: [
            { title: "14 ayar altın nasıl hesaplanır?", body: "14 ayar altında gram miktarı 0,583 has altın oranıyla çarpılır ve çıkan has altın miktarı güncel gram altın fiyatıyla değerlendirilir." },
            { title: "14 ayar altın kaç milyem, neden daha ucuz?", body: "14 ayar, adından geldiği gibi 24 birimin 14'ü kadar saf altın içerir: 14 bölü 24 işlemi 0,583 oranını, yani 583 milyemi verir. Milyem, bin birim alaşımda kaç birim saf altın bulunduğunu gösterir; buna göre bin birimin 583'ü saf altın, kalan yaklaşık 417 birimi ise bakır, gümüş ve çinko gibi alaşım metalleridir. Ürünlerin üzerinde çoğunlukla 583 değil 585 damgasını görürsünüz: 585, kuyumculukta ve uluslararası damga standardında yerleşmiş yuvarlanmış değerdir ve üreticiye küçük bir tolerans payı bırakır. İkisi arasındaki fark binde iki düzeyindedir, yani 10 gramlık bir üründe yaklaşık 0,02 gram has altına denk gelir ve pratikte fiyata yansımaz. Bu sayfadaki hesaplamalarda matematiksel karşılık olan 0,583 oranı kullanılır. Gram fiyatının 22 ve 24 ayardan belirgin biçimde düşük olmasının nedeni ise bu orandır: 14 ayar bir ürünün her gramında 24 ayarın yaklaşık yüzde 58'i, 22 ayarın ise yaklaşık üçte ikisi kadar has altın bulunur. Yani fiyat farkı bir kalite ya da marka farkı değil, doğrudan içerdiği saf altın miktarının farkıdır. Aynı ağırlıktaki bir 14 ayar künye ile bir 22 ayar bilezik tartıda eşit görünse bile, içlerindeki has altın miktarı ve dolayısıyla değerleri birbirinden oldukça uzaktır. Bu yüzden 14 ayar üründe fiyatı değerlendirirken ağırlığa değil, milyemle çarpılmış has karşılığına bakmak gerekir." },
            { title: "14 ayar hesaplama (Örnek)", body: "8 gram ağırlığında 14 ayar bir kolyeyi ele alalım ve gram has altın alış fiyatının 5.000 TL olduğunu varsayalım. İlk adımda has altın karşılığı bulunur: 8 × 0,583 = 4,664 gram saf altın. İkinci adımda bu miktar alış fiyatıyla değerlendirilir: 4,664 × 5.000 = 23.320 TL. Bozdurmada eline geçen tutar bu civarda olur; kuyumcunun işlem payı nedeniyle pratikte bir miktar altında kalabilir. Karşılaştırma için aynı 8 gram 22 ayar olsaydı has karşılığı 8 × 0,917 = 7,336 gram olacak ve 36.680 TL'ye denk gelecekti. Aradaki yaklaşık 13.360 TL'lik fark, tamamen milyem farkından doğar; ağırlık her iki üründe de aynıdır. Buradaki rakamlar yalnızca örnektir, güncel fiyatlar sayfadaki canlı tabloda yer alır." },
            { title: "14 ayar altın neden tercih edilir? (Dayanıklılık)", body: "14 ayarın asıl gücü fiyatında değil, alaşımının sertliğindedir. Saf altın yumuşak bir metaldir; ayar düştükçe alaşım oranı arttığı için ürün sertleşir ve günlük kullanımda çizilmeye, ezilmeye ve şeklini kaybetmeye karşı daha dirençli hale gelir. Bu nedenle sürekli takılan yüzükler, ince bileklikler ve zincir kolyeler 14 ayarda üretildiğinde uzun süre formunu korur; aynı ürün 22 ayarda yapılsaydı kısa sürede ovalleşir ve yüzey çizikleri belirginleşirdi. Sert alaşım ayrıca ince işçiliğe ve hassas montüre imkân verir: taşlı yüzüklerde tırnak yuvası, kolye kilidi ve zincir baklaları gibi ince parçalar 14 ayarda daha güvenli tutar, taşın düşme riski azalır. Avrupa ve ithal takı üretiminde 14 ayarın yaygın standart olmasının nedeni de budur; oradaki takı kültürü altını birikim aracı olarak değil, giyilen bir aksesuar olarak konumlandırdığı için dayanıklılık ve tasarım özgürlüğü öne çıkar. Türkiye'de de günlük kullanım takılarında, çocuk takılarında ve beyaz altın modellerinde 14 ayar sıkça karşımıza çıkar." },
            {
                title: "14 ayar bozdurmada ne kaybettirir?",
                body: "14 ayar bir ürün bozdurulurken hesabın mantığı diğer tüm altınlarla aynıdır: ağırlık milyemle çarpılır, çıkan has altın güncel alış fiyatıyla değerlendirilir. Fark, sonucun düşük çıkmasındadır. Düşük has oranı nedeniyle aynı ağırlıktaki bir ürün 22 ayara göre belirgin biçimde az tutar getirir; bu bir kayıp değil, ürünün baştan beri daha az altın içermesinin doğal sonucudur. Asıl kayıp kalemi işçilik payıdır: 14 ayar ürünler çoğunlukla ince işçilikli, tasarım ağırlıklı takılardır ve alım fiyatının içindeki işçilik oranı, üründeki altın değerine kıyasla yüksektir. Bozdurmada bu bedel karşılık bulmaz, çünkü ürün eritilip yeniden işlenmek üzere has değeri üzerinden devralınır. İkinci bir etken küçük gramajdır; 14 ayar takılar genellikle hafif olduğu için toplam tutar düşük kalır ve sabit işlem payları oransal olarak daha fazla hissedilir. Ayrıca taş yuvası, kilit ve lehimli birleşim noktaları saf altın sayılmaz ve tartıdan düşülebilir. Bu tablo, 14 ayarın yatırımdan çok kullanım altını olarak konumlandığını gösterir: alım kolaylığı ve dayanıklılık sunar, buna karşılık nakde dönüşte 22 ayar kadar güçlü değildir. Genel bozdurma süreci, nerede bozdurmanın avantajlı olduğu ve tüm kayıp kalemleri için altın bozdurma sayfasına bakabilirsiniz.",
                links: [
                    { label: "Altın bozdurma hesaplama", href: "/finansal-hesaplamalar/altin-bozdurma-hesaplama" },
                    { label: "Gram altın hesaplama", href: "/finansal-hesaplamalar/gram-altin-hesaplama" },
                    { label: "18 ayar altın hesaplama", href: "/finansal-hesaplamalar/18-ayar-altin-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "14 ayar altın kaç milyem?", answer: "14 ayarın matematiksel karşılığı 583 milyemdir: 14 bölü 24 işlemi 0,583 oranını verir, yani bin birim alaşımın 583 birimi saf altındır. Kalan yaklaşık 417 birim bakır, gümüş ve çinko gibi alaşım metallerinden oluşur ve ürüne sertliğini kazandıran kısım budur. Ürünlerin üzerinde ise çoğunlukla 585 damgası bulunur; 585 kuyumculukta ve uluslararası damga standardında yerleşmiş yuvarlanmış değerdir. Aradaki binde iki düzeyindeki fark pratikte fiyata yansımaz. Karşılaştırma için 18 ayar 750, 22 ayar 916, 24 ayar ise 995 ve üzeri milyeme karşılık gelir." },
            { question: "14 ayar altın kaç TL?", answer: "14 ayar altının TL karşılığı sabit değildir; ons altın fiyatı ve dolar/TL kuru gün içinde hareket ettikçe değişir. Hesap, gram ağırlığın 0,583 ile çarpılıp çıkan has altın miktarının güncel gram fiyatıyla değerlendirilmesiyle yapılır. Has oranı düşük olduğu için 14 ayarın gram birim fiyatı, 22 ve 24 ayar fiyatlarının belirgin biçimde altında kalır. Bu sayfadaki tabloda son bilinen alış ve satış fiyatı gösterilir; bozdurma yapacaksanız alış, alım yapacaksanız satış fiyatı sizin için geçerli olan rakamdır." },
            { question: "14 ayar altın neden daha ucuz?", answer: "Çünkü içinde daha az saf altın vardır. 14 ayarın her gramında yaklaşık 0,583 gram has altın bulunurken 22 ayarda bu oran 0,917, 24 ayarda ise 0,995 ve üzeridir. Fiyat farkı bir kalite veya işçilik farkından değil, doğrudan bu has oranı farkından doğar. Kalan kısmı oluşturan bakır ve gümüş gibi metaller altına göre çok düşük değerlidir, ancak ürüne sertlik kazandırır. Bu nedenle aynı gramajdaki bir 14 ayar ürün, bir 22 ayar üründen hem alımda hem bozdurmada belirgin biçimde ucuzdur." },
            { question: "14 ayar altın yatırımlık mı?", answer: "14 ayar genel olarak yatırım aracı değil, kullanım altını olarak konumlanır ve bu bir tavsiye değil, ürünün yapısına ilişkin bir tespittir. Düşük has oranı nedeniyle aynı ağırlıkta daha az saf altın taşır; ayrıca bu ayardaki ürünler çoğunlukla ince işçilikli takılar olduğu için alım fiyatındaki işçilik payı yüksektir ve bozdurmada geri alınamaz. Buna karşılık dayanıklılığı sayesinde günlük kullanımda uzun ömürlüdür ve giriş maliyeti düşüktür. Saf altın biriktirmek önceliğinizse gram altın veya yüksek ayarlı ürünler bu amaca daha uygundur; takı olarak kullanmak öndeyse 14 ayar işlevini yerine getirir." },
            { question: "14 ayar mı 18 ayar mı?", answer: "İkisi arasındaki seçim, dayanıklılık ile has oranı arasında bir dengedir. 14 ayar 583 milyemle (piyasada 585 damgasıyla) daha az altın içerir, buna karşılık alaşımı daha sert olduğu için günlük yoğun kullanımda çizilme ve deformasyona karşı daha dirençlidir; giriş maliyeti de düşüktür. 18 ayar ise 750 milyemle belirgin biçimde daha fazla has altın taşır, rengi daha dolgundur ve bozdurmada aynı gramajda daha yüksek karşılık verir, ancak 14 ayara göre bir miktar daha yumuşaktır. Sürekli takılan ince bir yüzük veya zincir için 14 ayar öne çıkarken, hem kullanım hem değer saklama beklentisi varsa 18 ayar dengeyi daha yukarı taşır. 18 ayarın kendi milyem hesabı ve örnekleri için ilgili sayfaya bakabilirsiniz." },
        ],
    },
    "18-ayar-altin-hesaplama": {
        slug: "18-ayar-altin-hesaplama",
        title: "18 Ayar Altın Hesaplama 2026 - 18 Ayar Altın Kaç TL?",
        metaDescription: "18 ayar altın gramını 750 milyem has oranıyla hesaplayın. Pırlanta montürü, 14 ve 22 ayar farkı, bozdurma değeri örnekle.",
        h1: "18 Ayar Altın Hesaplama - 18 Ayar Altın Kaç TL?",
        intro: "18 ayar altın 750 milyemdir; her gramın 0,750 gramı has altındır. Gram miktarına göre yaklaşık TL değerini görün.",
        targetQueries: ["18 ayar altın hesaplama", "18 ayar altın kaç TL", "18 ayar altın bozdurma", "18 ayar altın kaç milyem"],
        goldType: "gram18k",
        mode: "bozdurma",
        amount: 10,
        content: [
            { title: "18 ayar altın nasıl hesaplanır?", body: "18 ayar altında gram miktarı 750 milyem, yani 0,750 has altın oranıyla çarpılır ve çıkan has altın miktarı güncel gram altın fiyatıyla değerlendirilir. Alımda satış, bozdurmada alış fiyatı kullanılır." },
            { title: "18 ayar altın kaç milyem?", body: "18 ayar tam olarak 750 milyeme karşılık gelir: 18 bölü 24 işlemi 0,750 oranını verir, yani bin birim alaşımın 750 birimi saf altındır. Kalan 250 birim bakır, gümüş, paladyum veya çinko gibi metallerden oluşur ve bu alaşım hem ürünün sertliğini hem de rengini belirler. Aynı 18 ayar oran içinde farklı alaşım bileşimleriyle sarı, beyaz ve rose altın üretilir; üçünün de has altın oranı 750'dir, aralarındaki fark yalnızca kalan 250 birimin hangi metallerden oluştuğudur. 18 ayarın diğer ayarlardan ayrılan yönü, ayar merdiveninde tam orta segmentte durmasıdır: 14 ayarın 583 milyemine göre belirgin biçimde daha fazla altın içerir, 22 ayarın 916 milyemine göre ise daha az. Bu konum ona saflık ile dayanıklılık arasında dengeli bir yer kazandırır; altın oranı değer saklamaya yetecek kadar yüksek, alaşım oranı ise işlenebilirlik ve sağlamlık sağlayacak kadar belirgindir. Milyem sayısı yuvarlama gerektirmeden tam çıktığı için 18 ayarda damga ile hesap oranı birebir örtüşür." },
            { title: "18 ayar hesaplama (Örnek)", body: "12 gram ağırlığında 18 ayar bir künyeyi ele alalım ve gram has altın alış fiyatının 5.000 TL olduğunu varsayalım. İlk adımda has altın karşılığı bulunur: 12 × 0,750 = 9 gram saf altın. İkinci adımda bu miktar alış fiyatıyla değerlendirilir: 9 × 5.000 = 45.000 TL. Bozdurmada eline geçen tutar bu civarda olur; kuyumcunun işlem payı nedeniyle pratikte bir miktar altında kalabilir. Karşılaştırma için aynı 12 gram 14 ayar olsaydı has karşılığı 12 × 0,583 = 6,996 gram, yani yaklaşık 34.980 TL; 22 ayar olsaydı 12 × 0,917 = 11,004 gram, yani yaklaşık 55.020 TL olacaktı. Üç ayarın aynı gramajdaki tablosu, 18 ayarın neden orta yol sayıldığını doğrudan gösterir. Buradaki rakamlar yalnızca örnektir; güncel fiyatlar sayfadaki canlı tabloda yer alır." },
            { title: "18 ayar altın nerede kullanılır? (Montür)", body: "18 ayarın en yaygın kullanım alanı taşlı takı montürüdür. Pırlanta, safir ve zümrüt gibi taşlar, metal tırnaklar veya kanal yuvalar içine sıkıştırılarak sabitlenir; bu tırnakların taşı yıllarca kavraması için hem sert hem de yorulmaya dayanıklı bir metal gerekir. 22 ayar bu iş için fazla yumuşaktır: tırnaklar zamanla açılır, taş oynamaya başlar ve düşme riski doğar. 14 ayar yeterince serttir ancak daha kırılgan bir davranış gösterebilir ve altın oranı düşük olduğu için değerli taş taşıyan bir üründe genellikle tercih edilmez. 18 ayar bu iki uç arasında en dengeli seçenektir; hem tırnağı güvenle tutar hem de üründeki altın değerini yüksek düzeyde korur. Bu nedenle pırlanta yüzük, tektaş ve markalı tasarım takı üretiminde 18 ayar fiili standarttır. İkinci bir etken renk esnekliğidir: beyaz altın ve rose altın gibi tonlar 18 ayarda temiz biçimde elde edilebilir, çünkü kalan 250 birimlik alaşım rengi belirleyecek kadar geniştir. Avrupa'da 750 damgası yerleşik bir standarttır ve ithal markalı takıların çoğu bu ayarda üretilir; Türkiye'de de kuyum sektörü ihracat ürünlerinde ağırlıklı olarak 18 ayar çalışır." },
            {
                title: "18 ayar: takı mı yatırım mı?",
                body: "18 ayar, ayar skalasında iki uç arasında konumlandığı için hem takı hem birikim tarafında kısmi bir karşılık bulur; aşağıdakiler bir tavsiye değil, ürünün yapısına ilişkin tespitlerdir. Değer tarafında 14 ayara göre açık bir üstünlüğü vardır: her gramda 0,750 gram has altın taşır, yani aynı ağırlıktaki bir 14 ayar üründen yaklaşık yüzde 29 daha fazla saf altın içerir ve bozdurmada bu fark doğrudan tutara yansır. Kullanım tarafında ise 22 ayara göre avantajlıdır; sert alaşımı sayesinde ince işçiliğe, taş montürüne ve sürekli takılmaya 22 ayardan çok daha iyi dayanır. Buna karşılık saf altın biriktirme amacı tek başına öndeyse 18 ayar ideal araç değildir: gram başına has altın oranı 22 ayarın ve gram altının altındadır, ayrıca bu ayardaki ürünler çoğunlukla tasarım ağırlıklı olduğu için alım fiyatındaki işçilik ve marka payı yüksektir ve bu pay bozdurmada geri alınmaz. Taşlı ürünlerde ek bir ayrıntı vardır: bozdurmada yalnızca metalin has altın karşılığı hesaplanır, pırlanta veya diğer taşlar kuyumcu tarafından ayrı değerlendirilir ya da hiç fiyatlanmaz. Kısacası 18 ayar, kullanılacak ama değerini de koruması istenen ürünlerde dengeyi kuran ayardır; yalnız yatırım hedefleniyorsa primi ve işçiliği düşük ürünler bu amaca daha uygundur.",
                links: [
                    { label: "Altın bozdurma hesaplama", href: "/finansal-hesaplamalar/altin-bozdurma-hesaplama" },
                    { label: "Gram altın hesaplama", href: "/finansal-hesaplamalar/gram-altin-hesaplama" },
                    { label: "22 ayar bilezik hesaplama", href: "/finansal-hesaplamalar/22-ayar-bilezik-hesaplama" },
                ],
            },
        ],
        faq: [
            { question: "18 ayar altın kaç milyem?", answer: "18 ayar 750 milyemdir; 18 bölü 24 işlemi 0,750 oranını verir, yani bin birim alaşımın 750 birimi saf altındır. Kalan 250 birim bakır, gümüş, paladyum veya çinko gibi metallerden oluşur ve ürünün hem sertliğini hem rengini belirler. Sarı, beyaz ve rose altın modellerin üçünde de has oran 750'dir; fark yalnızca alaşımın bileşimindedir. Karşılaştırma için 14 ayar 583, 22 ayar 916, 24 ayar ise 995 ve üzeri milyeme karşılık gelir." },
            { question: "18 ayar altın kaç TL?", answer: "18 ayar altının TL karşılığı sabit değildir; ons altın fiyatı ve dolar/TL kuru gün içinde hareket ettikçe değişir. Hesap, gram ağırlığın 0,750 ile çarpılıp çıkan has altın miktarının güncel gram fiyatıyla değerlendirilmesiyle yapılır. Bu sayfadaki tabloda son bilinen alış ve satış fiyatı gösterilir; bozdurma yapacaksanız alış, alım yapacaksanız satış fiyatı sizin için geçerli olan rakamdır. Taşlı ürünlerde hesap yalnızca metalin has altın karşılığını verir, taşın değeri bu tutara dahil değildir." },
            { question: "18 ayar mı 22 ayar mı?", answer: "İkisi farklı önceliklere hizmet eder. 22 ayar 916 milyemle belirgin biçimde daha fazla has altın taşır, bu nedenle aynı gramajda bozdurma değeri yüksektir ve Türkiye'de bilezik ile geleneksel ziynet takısının standardıdır; birikim amacına daha uygundur. 18 ayar ise 750 milyemle daha az altın içerir, buna karşılık alaşımı daha sert olduğu için ince işçiliğe, taş montürüne ve sürekli kullanıma çok daha dayanıklıdır; ayrıca beyaz ve rose gibi renk seçeneklerine imkân verir. Değer saklamak öndeyse 22 ayar, kullanılacak ve taş taşıyan bir ürün gerekiyorsa 18 ayar öne çıkar." },
            { question: "Pırlanta yüzük neden 18 ayar olur?", answer: "Çünkü taşı tutan tırnakların sağlam olması gerekir. Pırlanta, metal tırnaklar veya kanal yuva içine sıkıştırılarak sabitlenir ve bu ince parçaların yıllarca açılmadan kavraması için sert bir alaşım şarttır. 22 ayar bu iş için fazla yumuşaktır; tırnaklar zamanla açılır ve taşın oynama ya da düşme riski doğar. 18 ayar hem gerekli sertliği sağlar hem de 750 milyemle üründeki altın değerini yüksek tutar, bu yüzden tektaş ve markalı takı üretiminde fiili standart haline gelmiştir. Ayrıca beyaz altın tonu 18 ayarda temiz biçimde elde edildiği için pırlanta ile birlikte tercih edilir." },
            { question: "18 ayar altın yatırımlık mı?", answer: "18 ayar, kullanım ile değer saklama arasında dengeli bir üründür ve bu bir tavsiye değil, yapısına ilişkin bir tespittir. 14 ayara göre gram başına yaklaşık yüzde 29 daha fazla has altın taşıdığı için bozdurmada belirgin biçimde daha güçlüdür. Buna karşılık gram başına altın oranı 22 ayarın ve gram altının altındadır; ayrıca bu ayardaki ürünler çoğunlukla tasarım ve marka ağırlıklı olduğu için alım fiyatındaki işçilik payı yüksektir ve bozdurmada geri alınamaz. Taşlı ürünlerde yalnızca metalin has karşılığı hesaplanır. Saf altın biriktirmek tek hedefse gram altın veya yüksek ayarlı ürünler bu amaca daha uygundur; takı olarak kullanılacaksa 18 ayar değeri en iyi koruyan seçeneklerdendir." },
        ],
    },
};

export const GOLD_LONG_TAIL_SLUGS = Object.keys(GOLD_LONG_TAIL_PAGES) as GoldLongTailSlug[];

export function getGoldLongTailPage(slug: GoldLongTailSlug) {
    return GOLD_LONG_TAIL_PAGES[slug];
}
