import type { Metadata } from "next";
import Link from "@/components/analytics/TrackedLink";
import { ArrowRight, CheckCircle2, ChevronRight, Code2, Layers3, MessageSquareText, ShieldCheck } from "lucide-react";
import CorporateCta from "@/components/corporate/CorporateCta";
import CorporateSchema from "@/components/corporate/CorporateSchema";
import { corporateServices, CORPORATE_CONTACT_PATH } from "@/lib/corporate-services";
import { SITE_NAME, SITE_URL } from "@/lib/site";

const title = "HesapMod Kurumsal Yazılım Çözümleri";
const description = "İşletmenize özel web, mobil, masaüstü, entegrasyon, otomasyon ve SaaS çözümleri; analizden canlıya geçiş ve bakıma uçtan uca yazılım geliştirme.";

export const metadata: Metadata = {
    title: { absolute: `${title} | ${SITE_NAME}` }, description,
    alternates: { canonical: `${SITE_URL}/kurumsal` },
    openGraph: { title, description, url: `${SITE_URL}/kurumsal`, siteName: SITE_NAME, type: "website", locale: "tr_TR", images: [{ url: `${SITE_URL}/opengraph-image`, width: 1200, height: 630, alt: title }] },
    twitter: { card: "summary_large_image", title, description, images: [`${SITE_URL}/opengraph-image`] },
};

const serviceAreas = ["Özel yazılım geliştirme", "Web uygulamaları", "Android/iOS mobil uygulamalar", "Masaüstü yazılımlar", "API ve sistem entegrasyonları", "İş süreçleri otomasyonu", "SaaS ve abonelik sistemleri", "Yönetim panelleri ve raporlama", "Mevcut yazılım geliştirme", "Bakım ve teknik destek"];
const process = ["İhtiyaç analizi", "Çözüm ve mimari tasarımı", "Prototip ve kapsam onayı", "Geliştirme, entegrasyon ve test", "Canlıya geçiş, bakım ve destek"];
const skills = ["Sistem ve ihtiyaç analizi", "Backend ve API geliştirme", "Mobil uygulama geliştirme", "Web uygulama geliştirme", "Entegrasyon", "Otomatik ve manuel test", "Devreye alma ve teknik destek"];

export default function CorporatePage() {
    return <main className="min-w-0 max-w-full bg-slate-50 text-slate-900">
        <CorporateSchema />
        <section className="relative overflow-hidden bg-gradient-to-br from-[#211712] via-[#68361F] to-[#B83A12] text-white"><div className="pointer-events-none absolute -right-24 -top-24 h-96 w-96 rounded-full border border-white/10" /><div className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8"><nav aria-label="Sayfa yolu" className="flex items-center gap-1 text-sm text-orange-100"><Link href="/" className="rounded-sm hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Ana Sayfa</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">Kurumsal Yazılım</span></nav></div><div className="mx-auto grid max-w-7xl gap-12 px-4 pb-16 pt-10 sm:px-6 sm:pb-24 lg:grid-cols-[1.2fr_.8fr] lg:items-center lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-orange-200">HesapMod Kurumsal</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-tight sm:text-5xl lg:text-6xl">HesapMod Kurumsal Yazılım Çözümleri</h1><p className="mt-6 max-w-3xl text-xl font-semibold leading-relaxed text-white">İşletmenize özel web, mobil, masaüstü, entegrasyon ve SaaS çözümleri geliştiriyoruz.</p><p className="mt-4 max-w-3xl leading-relaxed text-orange-50">İş süreçlerinizi analiz ediyor, ihtiyacınıza uygun yazılım mimarisini tasarlıyor ve güvenli, sürdürülebilir uygulamalara dönüştürüyoruz.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={CORPORATE_CONTACT_PATH} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-6 py-3 font-bold text-[#9E3515] transition hover:bg-orange-50 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/60"><MessageSquareText size={19} aria-hidden="true" /> Projenizi Anlatın</Link><Link href="#cozumler" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/40 px-6 py-3 font-bold text-white transition hover:bg-white/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/50">Çözümleri İnceleyin <ArrowRight size={18} aria-hidden="true" /></Link></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{[{ icon: Code2, title: "İhtiyaca özel", text: "Hazır kalıplar yerine gerçek süreç ve kullanıcı rollerine göre kapsam." }, { icon: Layers3, title: "Uçtan uca yaklaşım", text: "Analiz, mimari, geliştirme, entegrasyon, test ve canlıya geçiş." }, { icon: ShieldCheck, title: "Sürdürülebilir temel", text: "Güvenlik, bakım ve büyüme ihtiyaçlarını baştan ele alan yapı." }].map(({icon: Icon,title,text}) => <div key={title} className="rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur"><Icon aria-hidden="true" className="text-orange-200" /><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mt-1 text-sm leading-relaxed text-orange-50">{text}</p></div>)}</div></div></section>
        <section id="cozumler" className="scroll-mt-24"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12]">Çözümler</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">İş sürecine uygun yazılım hizmetleri</h2><p className="mt-4 leading-relaxed text-slate-600">Yeni bir ürün geliştirmekten mevcut sistemi iyileştirmeye kadar, teknik kapsamı iş hedefleriyle birlikte ele alıyoruz.</p></div><div className="mt-8 flex flex-wrap justify-center gap-4">{corporateServices.map(service => <Link key={service.slug} href={`/kurumsal/${service.slug}`} className="group flex w-full flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-orange-300 hover:shadow-lg focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 md:w-[calc(50%_-_0.5rem)] xl:w-[calc(25%_-_0.75rem)]"><h3 className="text-lg font-black text-slate-950 group-hover:text-[#B83A12]">{service.shortTitle}</h3><p className="mt-3 flex-1 text-sm leading-relaxed text-slate-600">{service.shortDescription}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#B83A12]">Hizmeti incele <ArrowRight size={15} aria-hidden="true" /></span></Link>)}</div></div></section>
        <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-center lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12]">İş sorununuza göre başlayın</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950">Hazır hizmet adından önce çözmek istediğiniz süreci seçin</h2><p className="mt-3 max-w-3xl leading-relaxed text-slate-600">Excel ve manuel işler, otomasyon, raporlama, stok, saha ve müşteri takibi için çözüm yaklaşımlarını inceleyin.</p></div><Link href="/cozumler" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#B83A12] px-6 py-3 font-bold text-white hover:bg-[#962F10] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-300">İşletme Çözümleri <ArrowRight size={18} aria-hidden="true" /></Link></div></section>
        <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12]">Hizmet alanları</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950">İhtiyaçtan operasyona geniş kapsam</h2></div><div className="grid gap-3 sm:grid-cols-2">{serviceAreas.map(item => <div key={item} className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm font-semibold text-slate-700"><CheckCircle2 size={18} className="shrink-0 text-[#B83A12]" aria-hidden="true" />{item}</div>)}</div></div></div></section>
        <section><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12]">Çalışma yöntemi</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950">Beş aşamada kontrollü ilerleme</h2><ol className="mt-8 grid gap-4 md:grid-cols-5">{process.map((item,index)=><li key={item} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="text-sm font-black text-[#B83A12]">0{index+1}</span><h3 className="mt-3 font-bold leading-snug text-slate-950">{item}</h3></li>)}</ol></div></section>
        <section className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12]">Ekip yetkinlikleri</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950">Bir yazılımın yaşam döngüsü için gereken disiplinler</h2><p className="mt-4 leading-relaxed text-slate-600">İhtiyaçları teknik kararlara dönüştüren ve teslim sonrasını da hesaba katan yetkinlikleri proje kapsamında bir araya getiriyoruz.</p></div><div className="mt-8 flex flex-wrap gap-3">{skills.map(skill=><span key={skill} className="rounded-full border border-slate-200 bg-slate-50 px-4 py-2 text-sm font-semibold text-slate-700">{skill}</span>)}</div></div></section>
        <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><CorporateCta /></div>
        <section className="border-y border-slate-200 bg-orange-50 dark:border-slate-800 dark:bg-orange-950/20"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-10 sm:px-6 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#B83A12] dark:text-orange-300">Ön kapsam aracı</p><h2 className="mt-2 text-2xl font-black text-slate-950 dark:text-white">Projenizin kapsamını yedi adımda netleştirin</h2><p className="mt-2 max-w-3xl text-slate-600 dark:text-slate-300">Süre bandını, ilk fazı ve kritik teknik başlıkları ücretsiz ön değerlendirmeyle görün.</p></div><Link href="/kurumsal/yazilim-projesi-kapsam-hesaplama" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#B83A12] px-6 py-3 font-bold text-[#B83A12] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-orange-200 dark:text-orange-300">Kapsamı Hesapla <ArrowRight size={18} aria-hidden="true" /></Link></div></section>
    </main>;
}
